//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MKE_LABEntities : DbContext
    {
        private static MKE_LABEntities context;
        public MKE_LABEntities()
            : base("name=MKE_LABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static MKE_LABEntities GetContext()
        {
            if (context == null)
                context = new MKE_LABEntities();
            return context;
        }

        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Взыскание> Взыскание { get; set; }
        public virtual DbSet<Водители> Водители { get; set; }
        public virtual DbSet<Инспекторы_ДПС> Инспекторы_ДПС { get; set; }
        public virtual DbSet<Логирование> Логирование { get; set; }
        public virtual DbSet<Нарушение> Нарушение { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
