//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        public int Код { get; set; }
        public string Номер_автомобиля { get; set; }
        public int Номер_водительского_удостоверения { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public string Цвет { get; set; }
        public Nullable<int> Год_выпуска { get; set; }
        public System.DateTime Дата_регистрации_в_ГАИ { get; set; }
        public bool Данные_в_архив { get; set; }
    
        public virtual Водители Водители { get; set; }
    }
}
