//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Взыскание
    {
        public int Код_взыскания { get; set; }
        public System.DateTime Дата_и_время_нарушения { get; set; }
        public string Район_совершения_нарушения { get; set; }
        public Nullable<decimal> Размер_штрафа { get; set; }
        public bool Оплачен_штраф_или_не_оплачен { get; set; }
        public Nullable<int> Срок_лишения_права_управления_автомобилем { get; set; }
        public Nullable<decimal> Базовая_величина { get; set; }
        public int Личный_номер_инспектора_ДПС { get; set; }
        public bool Данные_в_архив { get; set; }
    
        public virtual Нарушение Нарушение { get; set; }
        public virtual Инспекторы_ДПС Инспекторы_ДПС { get; set; }
    }
}
