//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инспекторы_ДПС
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Инспекторы_ДПС()
        {
            this.Взыскание = new HashSet<Взыскание>();
        }
    
        public int Личный_номер_инспектора { get; set; }
        public string ФИО { get; set; }
        public string Отделение_ДПС { get; set; }
        public string Телефон { get; set; }
        public string Электронная_почта { get; set; }
        public bool Данные_в_архив { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Взыскание> Взыскание { get; set; }
    }
}
