//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Логирование
    {
        public int Код_записи { get; set; }
        public System.DateTime Время_входа { get; set; }
        public string Логин { get; set; }
        public Nullable<bool> Зашол_или_нет { get; set; }
        public string Примечание { get; set; }
    }
}
